Remove absolute binaries paths in scripts

diff --git a/.chezmoiscripts/linux/run_onchange_after_enable-toolbox-autoupdate-timer.sh.tmpl b/.chezmoiscripts/linux/run_onchange_after_enable-toolbox-autoupdate-timer.sh.tmpl
--- a/.chezmoiscripts/linux/run_onchange_after_enable-toolbox-autoupdate-timer.sh.tmpl
+++ b/.chezmoiscripts/linux/run_onchange_after_enable-toolbox-autoupdate-timer.sh.tmpl
@@ -7,11 +7,11 @@ if [[ ! -f /run/.toolboxenv ]]; then
 fi
 
 systemctl --user daemon-reload
-case $(/usr/bin/systemctl --user is-enabled toolbox-autoupdate.timer) in
+case $(systemctl --user is-enabled toolbox-autoupdate.timer) in
   enabled*)
     : ;;
   disabled)
-    /usr/bin/systemctl --user enable toolbox-autoupdate.timer ;;
+    systemctl --user enable toolbox-autoupdate.timer ;;
   masked*)
     echo "toolbox-autoupdate.timer is masked, not enabling." >&2 ;;
   bad)
@@ -19,5 +19,5 @@ case $(/usr/bin/systemctl --user is-enabled toolbox-autoupdate.timer) in
   not-found)
     echo "toolbox-autoupdate.timer not found." >&2 ;;
   *)
-    echo "Error occured while running /usr/bin/systemctl --user is-enabled toolbox-autoupdate.timer." >&2 ;;
+    echo "Error occured while running systemctl --user is-enabled toolbox-autoupdate.timer." >&2 ;;
 esac
